language: node_js
node_js:
  - '4.0.0'
  - '4.1.0'

install:
  # - npm config set registry http://23.251.144.68
  # Disable the spinner, it looks bad on Travis
  - 'npm config set spin false'
  # Log HTTP requests
  - 'npm config set loglevel http'
  - 'time npm install'

after_script:
  - 'npm run coveralls'

script:
  - 'gulp test'